### ISSUE TITLE
Errors in strand switching

### ISSUE THREAD

**Issue by SilasK** [AnantharamanLab/VIBRANT#15]
I've seen the update for v1.1 and (v1.2). Does this mean the results from previous runs are wrong?

I had contigs which were sorted by name and maybe length?

**Comment by KrisKieft** [comment]
Short answer: technically no, your previous runs are fine whether they were from v1.0.1 or v1.1.0, but v1.2.0 will give you the best results. Also, I apologize but I’m not sure what you mean in your second question.

Full answer: I came across a bug that was identifying the correct strand switching per scaffold, but then filtering the scaffold wrong later (seen in v1.0.1). This caused viruses to be incorrectly filtered out early in the workflow and some inconsistency between runs. I fixed the bug so that strand switch filtering worked properly (seen in v1.1.0). Therefore, everything in v1.1.0 is working just fine and v1.0.1 is still identifying viruses accurately. However, after running several tests it became apparent that strand switch filtering was detrimental to VIBRANT’s recall by filtering out too many viruses. I removed the entire strand switching filtering step to increase recall with basically no effect on false discovery (seen in v1.2.0). Strand switching was all done before the KEGG/Pfam/VOG annotations and neural network (see workflow), so the robustness of VIBRANT’s overall recall and accuracy was not modified. This change overall led to anywhere from a 0% to 5% increase in recall based on a couple tests.

Kris
