### ISSUE TITLE
about AMGs

### ISSUE THREAD

**Issue by jerceyli** [AnantharamanLab/VIBRANT#22]
Hi developers,

I had a little confuse about the new version VIBRANT.  It adds a table AMGs_annotations_xxx.tsv. That's  really helpful. Not all the genes in this table were designated as AMGs. This is understandable due to some viral structual genes and so on. However, I found that the marker genes of some microorganisms (obviously it should not occur in viral contigs) were not annotated as AMGs, such as dsrC.

**Comment by KrisKieft** [comment]
Hi jerceyli,

I apologize, but I am a bit confused by your question. First, there is no output file named "AMGs_annotations_(input).tsv". The closest file I would assume you mean is just "annotations_(input).tsv" which includes annotations for every protein, not just the AMGs. Please correct me if I am wrong in what you are referring to but I will continue to refer to that file.  

There is a column titled "AMG" which will let you know if a gene in an AMG or not. If you look at that column dsrC indeed does not get annotated an an AMG. There is a bit of irony in that example because I am currently working with phages that encode dsrC and I am labeling it as an AMG. The short answer why VIBRANT does not include it as an AMG is because KEGG does not have dsrC in a metabolic pathway. DsrC is a sulfur carrier protein and performs no enzymatic steps, so it was left out of the dissimilatory sulfate reduction pathway on KEGG. Since VIBRANT includes many examples of AMGs I streamlined the identification simply by including all genes within KEGG metabolic pathways. DsrA on the other hand, the enzyme involved with DsrC, is included as an AMG. It is difficult to manually identify each exception.  

Furthermore, marker genes for bacteria and other microbes aren't necessarily excluded from phage genomes. There are several examples of recA, dsrAC, ribosomal proteins and other "marker genes" being found on phage genomes. So if you find a marker gene you shouldn't automatically assume that it's contamination.  

I hope that helped but please let me know if you'd like further clarification.  

Kris

**Comment by jerceyli** [comment]
Hi Kris,

I am really sorry about my misuse of terminology and bad expression. Your reply perfectly answers my doubts. Thank you very much!

Jercey

**Comment by KrisKieft** [comment]
No problem at all! I appreciate that you are using VIBRANT and am always happy to answer questions.
