### ISSUE TITLE
Why do you not use the 99 release of VOG database?

### ISSUE THREAD

**Issue by kodragonP** [AnantharamanLab/VIBRANT#24]

**Comment by KrisKieft** [comment]
Hi,

When the VIBRANT project was started the current release was 94 of VOGdb. Since then I have not updated accordingly. Between release 94 and 99 few new VOGs have been added to the database and I do not believe it is significantly different enough to update at this point. There are about 1.5% more HMM profiles in the newest release. Virus recovery and accuracy have been benchmarked to release 94 and I am confident in the performance at this point. I hope that answers your question but feel free to ask for more clarification.  

Kris
