### ISSUE TITLE
Correct translation table?

### ISSUE THREAD

**Issue by Starfishgames** [AnantharamanLab/VIBRANT#3]
Greetings,
I would love to utilize your software, but first I would like to know whether it can identify the most appropriate translation table for the viral genome analyzed. This might impact the correct prediction of genes of phages infecting e.g. Mycoplasmatales or Gracilibacteria.

**Comment by KrisKieft** [comment]
Hi Starfishgames,  
Thank you for your interest in VIBRANT! VIBRANT utilizes Prodigal for all open reading frame predictions. Although Prodigal itself allows the user to indicate which translation table to use, within the VIBRANT script it's hardcoded to default (table 11). To my knowledge it will not estimate the best table for open reading frame prediction and will always be set to 11. That said, it's possible to edit VIBRANT and allow users to modify this setting. I will consider this. At this point if you suspect the wrong translation table is being used for a particular virus you can input your own protein predictions into VIBRANT instead of nucleotide (genome).  
  
Please let me know if you have any other comments or questions.  
Kris
