### ISSUE TITLE
Combined phage genbank file is invalid

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [AnantharamanLab/VIBRANT#34]
Hi,

Thanks for your work on VIBRANT! I am having a small issue parsing the genbank files of the combined phage annotations. It looks like the files are a mixture of tabs and spaces, which most tools that I have tried (BioPython, online services, etc) cannot parse. I would like to convert the file into a GFF3 if possible. Is there a way around this issue?

Thanks!

**Comment by KrisKieft** [comment]
Hi,

What specific information are you trying to parse? If I know your end goal or desired result I can help you out more effectively. Let me know and I'm happy to work through this with you.

Kris

**Comment by jdwinkler-lanzatech** [comment]
Thanks for the quick I'm trying to convert the generated genbank file for combined phages into a GFF file so I can more easily merge it with other annotation pipelines later on, if that helps. So nothing specific from the file.

**Comment by KrisKieft** [comment]
You may be able to get all the information you need from the phage protein file (combined.faa in the phages folder). In the definition line you'll have genomic location, strand and annotation name. I'm not familiar with the specifics of a gff file, what information do you need?

**Comment by jdwinkler-lanzatech** [comment]
Oh yes, I know that. GFFs are a lot more convenient though since there exist a lot more tools for handling them, and I'll need to output a combined GFF from a bunch of different annotation pipelines.

A good primer is here: https://uswest.ensembl.org/info/website/upload/gff.html

However, I think the fundamental issue is that the genbank file generated by VIBRANT is invalid and can't be read by external tools. If the genbank file were correct, I could just convert it myself using Biopython/BCBio without an issue. Specifically, it looks like the locus lines are misdefined and the file is a mixture of space/tab separators. If you give me some details concerning the internal genbank file generator you are using I might be able to suggest a more conformant parser?

**Comment by KrisKieft** [comment]
Which version of VIBRANT are you running? If I remember correctly I had accidentally replaced some spaces with tabs in a version prior to v1.2.1. I actually have the genbank file generated manually because it turned out to be easier, rather than use a parser. If you are not using v1.2.1 I'd suggest updating, running again, and see if that solves your issue. If not then I will look into this further.

**Comment by jdwinkler-lanzatech** [comment]
Yeah, I'm running v1.2.1 in docker, but let me check to make sure I'm using the correct conda package. Conda sometimes has odd version resolution.

**Comment by jdwinkler-lanzatech** [comment]
Is there a difference between the 1.2.1-1 and 1.2.1-0 tags on Conda? Here specifically: https://bioconda.github.io/recipes/vibrant/README.html

**Comment by KrisKieft** [comment]
To my knowledge they should be the same. Conda has an odd update system. I'll look into editing the genbank file. My only test was to upload it into a software called Geneious and that upload worked so I left the format alone. What software/package are you using to generate a gff file?

**Comment by jdwinkler-lanzatech** [comment]
Nothing fancy, just the following bit of code:

```
from Bio import SeqIO
from BCBio import GFF

GFF.write(SeqIO.parse('assembly.phages_combined.gbk', format='genbank'),
                open(os.path.join( 'vibrant_phage.gff'), 'w'))
```

Biopython==1.76 and BCBio==0.6.6. My colleague hasn't gotten back to me about importing an example genbank file into Geneious, but it may be more tolerant of different file formats than Biopython.

**Comment by KrisKieft** [comment]
I'll check out that code. I was able to upload a VIBRANT-generated genbank file into Geneious and export as a GFF3 file. Geneious is quite expensive if you don't have it. I also can't remember if there's a free version or only a free 2-week trial. But again, I'll look into fixing the format.

**Comment by KrisKieft** [comment]
Hi,

To my knowledge the issue has been resolved. The file `VIBRANT_run.py` has been updated to resolve the formatting issue with the genbank output file. The current version is still v1.2.1 and a new conda update was not pushed. To incorporate this update simply replace your old `VIBRANT_run.py` with the new one. Please let me know if this works for you and if not I can continue to look into resolving this. Thanks.

There are a couple of notes for this update regarding the specific python package you are using. The first one is an error to look out for and resolve manually and the second is a warning that can be ignored. 
* First, I believe biopython is expecting the names to be in Genbank format (e.g., NC_001331.1). It was giving me errors with certain symbols in the names. I did not look in detail at this to determine if the issue was spaces, commas, periods or something else. The error I was seeing was `ValueError: Did not recognise the LOCUS line layout`. By shortening the names this error went away. 
* Second, you will likely see the warning `BiopythonParserWarning: Attempting to parse malformed locus line` followed by the prompt `Some fields may be wrong`. I could not determine specifically why this warning was being generated but it didn't appear to effect the GFF output. To my knowledge you can just ignore this.

**Comment by jdwinkler-lanzatech** [comment]
Great, thanks. I had to solve a similar issue with VIRsorter since that tool has a similar problem with the locus tag length, so I can address that easily enough. Thanks for your help!

**Comment by a-89** [comment]
Hi Kris,

Many thanks for Vibrant, it is a great tool!! 

I replaced the old script with this new version to get the properly formatted .gbk file. When using the newer version from VIBRANT_run.py, it does not detect the KEGG HMM files. When using the older version, everything runs smoothly. I have all the required files in the share/vibrant-1.2.1/db/databases directory.

I get the following message "VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py"

Any suggestion on how to solve this issue?
Many thanks again!

Anna

**Comment by KrisKieft** [comment]
Hi,

It looks like you installed via conda, correct? This would end up being an issue with your conda environment and where it is looking. The easy/quick solution would just be to use the `-d` flag to specify `share/vibrant-1.2.1/db/databases`. Depending on the hierarchy of the folders, you may be able to just move the `databases` folder out of the `db` folder. VIBRANT natively looks for the databases in a folder called `databases` which should be located in the same directory as `VIBRANT_run.py`.

Kris

**Comment by a-89** [comment]
Thanks Kris, you are right! I solved the issue by copying the folder structure from the github.
