### ISSUE TITLE
setup with downloaded database file

### ISSUE THREAD

**Issue by liupfskygre** [AnantharamanLab/VIBRANT#39]
Hi, Kris,
     I want to setup vibrant on one of my server, however, I got a problem with net and could only transfer database downloaded instead of using wget. I have the 3 database files now. Do you have a way to setup up db separately with local downloaded files.

thanks.

**Comment by KrisKieft** [comment]
Hi,

Yes, this is definitely possible. Please note that in the normal setup script several of these are parallelized. If each item is run individually then this process will take a little while. If you happen to be familiar with Python code then you can follow the information in `VIBRANT_setup.py`, otherwise I have outlined the steps below for manually downloading, unzipping, combining and pressing the databases. Finally, please ensure you do not skip Step 8 below as it is important to verify everything is correct.

*Step 1*
Download these three links to the `databases/` folder in VIBRANT. Alternatively download elsewhere and use the `-d` flag when running VIBRANT. I suggest using these links as the database versions matter (VOG94, Pfam32.0, KEGG2019-08-10).
`http://fileshare.csb.univie.ac.at/vog/vog94/vog.hmm.tar.gz`
`ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/Pfam-A.hmm.gz`
`ftp://ftp.genome.jp/pub/db/kofam/archives/2019-08-10/profiles.tar.gz`

*Step 2*
Unzipping and untarring these files will generate a lot of files, so make sure you are doing this is the correct location.
`tar -xzf vog.hmm.tar.gz`
`gunzip Pfam-A.hmm.gz`
`tar -xzf profiles.tar.gz`

*Step 3*
This puts all the individual files back together
`for v in VOG*.hmm; do cat $v >> vog_temp.HMM; done`
`for k in profiles/K*.hmm; do cat $k >> kegg_temp.HMM; done`

*Step 4*
This deletes the individual files. For VOG this is run in steps because of the large number of files.
`rm VOG0*.hmm`
`rm VOG1*.hmm`
`rm VOG2*.hmm`
`rm -R profiles`

*Step 5*
Extract selected list of VOG and KEGG profiles. The folder `profiles_names` comes in the `databases` folder. Rename Pfam profiles
`hmmfetch -o VOGDB94_phage.HMM -f vog_temp.HMM profile_names/VIBRANT_vog_profiles.txt`
`hmmfetch -o KEGG_profiles_prokaryotes.HMM -f kegg_temp.HMM profile_names/VIBRANT_kegg_profiles.txt`
`mv Pfam-A.hmm Pfam-A_v32.HMM`

*Step 6* 
Remove excess
`rm vog_temp.HMM kegg_temp.HMM vog.hmm.tar.gz profiles.tar.gz`

*Step 7*
Press the HMM databases
`hmmpress VOGDB94_phage.HMM`
`hmmpress KEGG_profiles_prokaryotes.HMM`
`hmmpress Pfam-A_v32.HMM`

*Step 8* 
Verify databases were correctly downloaded/compiled and verify dependencies
`python3 VIBRANT_setup.py -test`

The final step will let you know if everything went well. Please let me know if you need further help.

Kris

**Comment by liupfskygre** [comment]
this is cool, thanks

**Comment by fconstancias** [comment]
HI @KrisKieft ,

I am having trouble setting upt the VIBRANT's database.

Everything seems smooth until the ```hmmfetch```command:

```ls
Pfam-A.hmm  VOGDB94_phage.HMM  kegg_temp.HMM  profiles.tar.gz  vog.hmm.tar.gz  vog_temp.HMM
```
```hmmfetch -o VOGDB94_phage.HMM -f vog_temp.HMM profile_names/VIBRANT_vog_profiles.txt```

> hmmfetch -o VOGDB94_phage.HMM -f vog_temp.HMM profile_names/VIBRANT_vog_profiles.txt
> 
> Error: Failed to open key file profile_names/VIBRANT_vog_profiles.txt
> 

Any idea what is going wrong? 

Thanks

**Comment by KrisKieft** [comment]
Hi,

Are you doing this manually or with the provided setup script?

**Comment by rotoscan** [comment]
Hello,

Step 5 for me is a bit unclear.
By the end of step 4, this is my database folder:

```
$ ls -lh
total 12G
-rw-r--r--. 1 nobody nobody 5,7G 20. Jan 13:22 kegg_temp.HMM
-rw-r--r--. 1 nobody nobody 1,4G 20. Jan 12:43 Pfam-A.hmm
-rw-r--r--. 1 nobody nobody 1,1G 20. Jan 13:07 profiles.tar.gz
-rw-r--r--. 1 nobody nobody 315M 21. Jun 2019  vog.hmm.tar.gz
-rw-r--r--. 1 nobody nobody 2,2G 20. Jan 13:18 vog_temp.HMM

```
And once I run the first command of step 5, here is what I get:
```
$ hmmfetch -o VOGDB94_phage.HMM -f vog_temp.HMM profile_names/VIBRANT_vog_profiles.txt

Error: Failed to open key file profile_names/VIBRANT_vog_profiles.txt


```
It is not clear to me what is going on. It clear expects the profile_names/VIBRANT_vog_profiles.txt to exist, but it is not there. Should I rename some other file to this file name?

Any help is appreciated!

Thanks
BEst
Rodolfo

**Comment by KrisKieft** [comment]
Hi,

You appear to be missing a folder called `profile_names`. That folder contains two files: `VIBRANT_kegg_profiles.txt` and `VIBRANT_vog_profiles.txt`. If you are missing that folder then you can download it from GitHub, found within the `databases` folder.

**Comment by rotoscan** [comment]
Thanks a lot @KrisKieft 

that worked!
