### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by slambrechts** [AnantharamanLab/VIBRANT#4]
Hi there,

Great effort! Correct me if I'm wrong, but I couldn't find any information regarding runtime in the paper or github page. Would you be able to provide some numbers regarding runtime for different kinds of assemblies? For example, I have a mixed assembly, generated using metaspades from soil metagenomes, which is about 1,1 Gigabytes in size. I would like to know if we are speaking about a matter of days, weeks, or rather hours, when running VIBRANT with standard parameters using only 1 thread? Or should I definitely specify more threads with such relatively big assemblies.

**Comment by KrisKieft** [comment]
Hi,

Thanks for the question, which is probably something that other people are wondering as well. This is somewhat of a difficult question to answer directly because runtime is very dependent on what your data looks like. If all 1.1GB is comprised of scaffolds that meet VIBRANT's minimum requirements (1kb, 4 proteins) then it will take longer than if, for example, 25% don't meet that cutoff. It also somewhat depends on how many viruses are in your dataset; regarding the workflow, non-viral scaffolds will be eliminated throughout the workflow, so fewer viruses will run faster. That said, for a 1.1 GB assembly I would suggest more than 1 thread if you have the capability. Running on CyVerse is an option if you have limited computing space (some details in the preprint). As just one example, I ran a 2GB assembly on CyVerse (specified 16 parallel runs) and it took 10 hours. Note, 97% of the dataset met VIBRANT's minimum requirements so it took much longer than for a normal assembly (this dataset was all limited to 5kb). Here are some other runtimes on our lab's server: 770MB assembly with 40 threads in 35 minutes, 250MB assembly with 5 threads in 2 hours. In summary, you should be looking at a timeline in hours, but if you find yourself with limited resources then CyVerse is a great option. You can find runtime in the log file after running. Hope that helps and thank you for using VIBRANT!

Kris

**Comment by KrisKieft** [comment]
![image](https://user-images.githubusercontent.com/35313603/72836685-c054f700-3c52-11ea-9048-23983e3128ba.png)
