### ISSUE TITLE
Scikit-learn

### ISSUE THREAD

**Issue by Thexiyang** [AnantharamanLab/VIBRANT#5]
Thanks for the nice tool! I installed Scikit-learn 0.21.2. However during the running procedure, it came with one warning asking me update to version 0.21.3, saying: use at your own risk. I did not do that as it conflicts with my other software. I checked the final output and all looked good. Is it OK to use version 0.21.2?

**Comment by KrisKieft** [comment]
Hi Thexiyang,

To my knowledge this should be just fine, especially since VIBRANT ran and looks good. Although v0.21.3 was used to build the machine learning model I do not believe it should impact reading the model. That part should mostly be dependent on Pickle (i.e., unpacking the model) which does require the up-to-date version. It appears you have that since VIBRANT ran. Feel free to let me know if you believe this is indeed causing any issues. Thanks for using VIBRANT!

Kris
