### ISSUE TITLE
lifestyle prediction

### ISSUE THREAD

**Issue by ucassee** [AnantharamanLab/VIBRANT#58]
Hello,

I was wondering how VIBRANT predicts the lifestyle of viruses?  What is the training data (marker proteins or whatever) you used to predict lifestyle? I don't find the detailed information in your paper, maybe I missed that.

Thanks

**Comment by KrisKieft** [comment]
Here's a quick summary. Let me know if you want any more details about it.

Prophage: see details in the manuscript on how prophages are excised. Basically, v-scores are used to cut at bacteria-like (low v-score) regions and then the excised sequence is run through the pipeline to see if it's a virus. Excised prophages are lysogenic.

Lysogenic: any virus that encodes an integrase-like annotation and all prophages.

Lytic: any virus not excised as a prophage and not identified as lysogenic (no integrase-like annotation). This category will be slightly over-estimated since any true lysogenic phage that is only a partial sequence without an integrase will be mis-identified as lytic.

**Comment by ucassee** [comment]
The summary is fine for me. 
Thanks for your quick reply!
