### ISSUE TITLE
Duplicates in VIBRANT_genome_quality TSV file

### ISSUE THREAD

**Issue by mshamash** [AnantharamanLab/VIBRANT#6]
Hello,

In going through the VIBRANT_genome_quality.tsv file generated by VIBRANT in the results folder, I noticed some contigs have two entries. 
The 'scaffold' and 'type' are the same for both entries of the duplicate, but the 'quality' is what is different between the two.

For example, I have one scaffold which is **lytic+complete circular**, but it will also have an entry as **lytic+low quality draft**.

Not sure if this is on purpose, or a bug, but I feel like each contig should only have one entry in this file?

Let me know if you need any more information to reproduce this. I can provide a sample scaffold which has this issue.

Best,

Michael

**Comment by KrisKieft** [comment]
Hi, 

Great observation. This is something that I originally noticed as a bug but decided to keep it. This specifically only happens when a scaffold is circular. That is, any complete circular scaffold will also be given a quality of high, medium or low. I apologize if this makes parsing the outputs difficult but my opinion was that it helped to give context to circular scaffolds. I am open to opinions on this and always appreciate comments. Let me know if you have or need any more clarification. Thanks for using VIBRANT! 

Kris

**Comment by mshamash** [comment]
Hi Kris,

Thanks for the quick response. It isn't that much extra work to deal with these few scaffolds, just wanted to confirm this was working as it should. I did have two ideas, just thought I'd bring them up and get your opinion:

-Since the VIBRANT_complete_circular TSV already has all the complete circular contigs with their 'type' (lytic/lysogenic), perhaps the genome_quality TSV should focus strictly on the 'quality' of the genome. When users want to know which are circular, they can check the complete_circular TSV file.

-Alternatively, a new column in the genome_quality TSV can be made, entitled "circular" which would have a "yes" or blank value for each contig. This would eliminate the need for duplicate contigs in the genome_quality TSV, since all info is on that same line.

Michael

**Comment by SilasK** [comment]
I don't understand, 
I understood `complete circular` as best quality. How can it be low quality at the same time?

**Comment by KrisKieft** [comment]
Hi Silas,

Unlike bacteria there is no clear way to estimate the completeness or quality of a viral genome. So far the only reliable metric is if the scaffold appears to be a circular template, though many viruses are linear in their natural form. Other people have used "complete circular" as a metric to estimate if a scaffold is complete, but even if the scaffold is 95% complete it wouldn't show up as circular. To address this issue, and include linear templates, I came up with estimation metrics for the completeness of a viral scaffold. Viruses are wildly different from one another so it's difficult to come up with a rule for all of them. The same issue can be found with bacteria and the newly identified CPR clade. In VIBRANT, identifying circular scaffolds and estimating completeness are two different measurements. Therefore you can have a circular template that was estimated to be low quality. For example, Myoviruses can encode hundreds of proteins but Microviridae have less than 10. When combining all viruses together it's easy to see that Microviridae, even complete ones, would likely fall under the category of low quality since they're so small. VIBRANT gives ALL scaffolds a completeness metric and identifies circular scaffolds. So circular scaffolds will end up with two labels. I hope that was clear enough! Scaffolds are considered circular based on nucleotide overlap at the 5' and 3' ends of the genome.

Kris
